name: Publish to NPM Automatically

on:
    push:
        branches:
            - main # Trigger on main branch push

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install dependencies
              run: npm install

            - name: Determine NPM Tag
              id: set-tag
              run: |
                  BRANCH_NAME=${GITHUB_REF#refs/heads/}
                  if [[ "$BRANCH_NAME" == "main" ]]; then
                    echo "TAG=latest" >> $GITHUB_ENV
                  else
                    echo "TAG=next" >> $GITHUB_ENV
                  fi

            - name: prepare
              run: npm run prepare

            - name: build
              run: npm run build

            - name: Publish to NPM with Tag
              run: npm publish --tag $TAG
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
